import os, re, glob

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(REPO, "docs")
SKIP = ("index.md", "about.md", "reports.md")
files = [f for f in glob.glob(DOCS + "/*.md") if os.path.basename(f) not in SKIP]

def meta(path):
    base = os.path.basename(path)[:-3]
    m = re.match(r"(\d{4}-\d{2}-\d{2})-(.+)", base)
    date, slug = m.group(1), m.group(2)
    title = base
    for line in open(path):
        if line.startswith("# "):
            title = line[2:].strip()
            break
    return date, slug, title

series_re = re.compile(r"^(.*)-part-(\d+)$")
groups = {}
standalone = []
for path in files:
    date, slug, title = meta(path)
    mm = series_re.match(slug)
    if mm:
        groups.setdefault(mm.group(1), []).append((int(mm.group(2)), date, slug, title))
    else:
        standalone.append((date, slug, title))

NAMES = {
    "blogging-skill-evolution": "Blogging Skill Evolution",
    "boot-recovery": "Boot Recovery",
    "captive-portal-and-access-point-bundle": "Captive Portal and Access Point Bundle",
    "coding-with-hermes-agent": "Coding with Hermes Agent",
    "experimenting-with-hermes-agent": "Experimenting with Hermes Agent",
    "hermes-agent-provider-and-fallback-chain": "Hermes Agent Provider and Fallback Chain",
    "homelab-management": "Homelab Management",
    "litellm-frontend-build": "LiteLLM Frontend Build",
    "mem0-memory-integration": "Mem0 Memory Integration",
    "opencode-configuration-evolution": "OpenCode Configuration Evolution",
    "opencode-provider-and-fallback-chain": "OpenCode Provider and Fallback Chain",
    "switch-root-target-contains-no-usable-init": "switch root target contains no usable init",
    "the-litellm-gateway-evolution": "The LiteLLM Gateway Evolution",
    "the-tinyllama-experiment": "The TinyLlama Experiment",
    "zensical-customization": "Zensical Customization",
}
def disp(key):
    return NAMES.get(key, key.replace("-", " ").title())

all_items = standalone + [(d, s, t) for k in groups for (_, d, s, t) in groups[k]]
latest10 = sorted(all_items, key=lambda x: x[0], reverse=True)[:10]

order = sorted(groups.items(), key=lambda kv: max(d for _, d, _, _ in kv[1]), reverse=True)

block = (
    '<div class="cb-home">\n'
    '  <div class="cb-home__top">\n'
    '    <section class="cb-hero">\n'
    '      <h1>Codebot Reports</h1>\n'
    '      <p>Collection of reports generated by Codebot from the blog markdown. '
    'Browse the series below, or the latest posts on the right.</p>\n'
    '    </section>\n'
    '    <aside class="cb-latest" aria-label="Latest posts">\n'
    '      <h2>Latest posts</h2>\n'
    '      <ul>\n'
)
for d, s, t in latest10:
    block += f'        <li><a href="/{s}/">{t}</a></li>\n'
block += '      </ul>\n    </aside>\n  </div>\n</div>\n'

lines = ["## Series", ""]
for key, items in order:
    items_sorted = sorted(items, key=lambda x: x[0])
    lines.append(f"### {disp(key)}")
    for _, date, slug, title in items_sorted:
        lines.append(f"- [{title}](/{slug}/)")
    lines.append("")

content = (
    "---\n"
    "nav_exclude: true\n"
    "hide:\n"
    "  - navigation\n"
    "---\n\n"
    + block
    + "\n"
    + "\n".join(lines)
    + "\n"
)

with open(os.path.join(DOCS, "index.md"), "w") as f:
    f.write(content)

print("wrote index.md")
print("series groups:", len(groups), "latest items:", len(latest10))
